# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('lock_id', models.CharField(max_length=10)),
                ('lock_state', models.CharField(max_length=2)),
                ('last_use_time', models.DateTimeField()),
            ],
        ),
    ]
