# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprintApp', '0002_auto_20170928_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockuse',
            name='finger_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lockuse',
            name='last_use_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lockuse',
            name='lock_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lockuse',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
