# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprintApp', '0003_auto_20170928_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockuse',
            name='finger_state',
        ),
    ]
