# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprintApp', '0004_remove_lockuse_finger_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockuse',
            name='lock_state',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
